# Site settings
name: Prabu Madhavan
title: Prabu Madhavan | Assistant Professor
description: 
url: maprabu.github.io
baseurl: ''
email: 
cover: 
logo: 
resume: 
social:
  # - title: email
    # url: mailto:brittany.chiang@gmail.com
  # - title: twitter
    # url: https://twitter.com/bchiang7
  # - title: instagram
    # url: https://instagram.com/bchiang7
  # - title: codepen
    # url: http://codepen.io/bchiang7
  # - title: github
    # url: https://github.com/bchiang7
  # - title: linkedin
    # url: https://www.linkedin.com/in/bchiang7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
